%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: G:\RunningCode\Original_Project\coor_ucat.csv
%
% Auto-generated by MATLAB on 12-Feb-2024 10:58:54

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["x", "y"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
coord_cell_centered = readtable("coor_cell_centered.csv", opts);
coord_ghost = readtable("coor_ghost.csv", opts);
coord_face_centered_x = readtable("coor_face_centered_x.csv", opts);
coord_face_centered_y = readtable("coor_face_centered_y.csv", opts);

%% Convert to output type
x_cc = coord_cell_centered.x;
y_cc = coord_cell_centered.y;

x_gh = coord_ghost.x;
y_gh = coord_ghost.y;

x_fc_x = coord_face_centered_x.x;
y_fc_x = coord_face_centered_x.y;

x_fc_y = coord_face_centered_y.x;
y_fc_y = coord_face_centered_y.y;

%text(x_ucat, y_ucat, 'c', 'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', 'FontSize', 10);
plot(x_gh, y_gh, 's');
hold on;
plot(x_cc, y_cc, 's', 'MarkerFaceColor', 'red');
plot(x_fc_x, y_fc_x, '>', 'MarkerFaceColor', 'cyan');
plot(x_fc_y, y_fc_y, '^', 'MarkerFaceColor', 'yellow');
grid on;

%% Clear temporary variables
clear opts tbl

delete("coor_cell_centered.csv");
delete("coor_ghost.csv");
delete("coor_face_centered_x.csv");
delete("coor_face_centered_y.csv");